[audio_extractor]
    [audio_extractor.whisper]
        model = "medium"
        device = "cpu"

[translator]
    [translator.deepl]
        api_key = ""
        target_lang = "KO"

[subtitle_generator]
    ext = "srt"